# Generated by Django 6.0.5 on 2026-05-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.IntegerField()),
                ('SchoolPhoneNo', models.IntegerField()),
                ('SchoolAddress', models.TextField()),
                ('SchoolEmail', models.EmailField(max_length=100)),
                ('PrincipleName', models.CharField(max_length=100)),
                ('PrinciplePhoneNo', models.IntegerField()),
                ('PrincipleEmail', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
