# Generated by Django 6.0.5 on 2026-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofilemodel',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='Students', to='StudentApp.studentprofilemodel'),
        ),
    ]
