# Generated by Django 6.0.5 on 2026-05-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='PrinciplePhoneNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
