# Generated by Django 6.0.5 on 2026-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_schoolprofilemodel_students'),
        ('StudentApp', '0002_alter_studentprofilemodel_schoolname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='Students', to='StudentApp.studentprofilemodel'),
        ),
    ]
