# Generated by Django 6.0.5 on 2026-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_alter_schoolprofilemodel_principlephoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='SchoolPhoneNo',
            field=models.IntegerField(null=True),
        ),
    ]
