# Generated by Django 6.0.5 on 2026-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_schoolprofilemodel_students'),
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofilemodel',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='TeacherApp.teacherprofilemodel'),
        ),
    ]
