# Generated by Django 6.0.5 on 2026-05-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_alter_schoolprofilemodel_schoolphoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchoolNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.schoolprofilemodel')),
            ],
        ),
    ]
