# Generated by Django 6.0.5 on 2026-05-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_schoolprofilemodel_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofilemodel',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
