# Generated by Django 6.0.6 on 2026-07-15 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_rename_teacher_schoolprofilemodel_teachers'),
        ('StudentApp', '0008_alter_coursemodel_studentclass_and_more'),
        ('TeacherApp', '0002_teacherprofilemodel_newschoolname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='StudentApp.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='TeacherApp.teacherprofilemodel'),
        ),
    ]
