# Generated by Django 6.0.6 on 2026-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_alter_schoolprofilemodel_admin_and_more'),
        ('StudentApp', '0008_alter_coursemodel_studentclass_and_more'),
        ('TeacherApp', '0002_teacherprofilemodel_newschoolname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='students',
            field=models.ManyToManyField(to='StudentApp.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='teachers',
            field=models.ManyToManyField(to='TeacherApp.teacherprofilemodel'),
        ),
    ]
