# Generated by Django 6.0.6 on 2026-07-15 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_alter_schoolprofilemodel_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofilemodel',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schoolUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
