# Generated by Django 6.0.6 on 2026-07-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0010_alter_schoolprofilemodel_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofilemodel',
            old_name='admin',
            new_name='user',
        ),
    ]
