# Generated by Django 6.0.5 on 2026-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofilemodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
