# Generated by Django 6.0.5 on 2026-06-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_rename_teacher_schoolprofilemodel_teachers'),
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='newSchoolName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacherSchool', to='SchoolApp.schoolprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='preSchoolName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
