# Generated by Django 6.0.5 on 2026-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='subjectId',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='studentId',
            new_name='student',
        ),
    ]
