# Generated by Django 6.0.5 on 2026-05-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_schoolprofilemodel_students'),
        ('StudentApp', '0001_initial'),
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.teacherprofilemodel'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='StudentApp.studentprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='schoolName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolName', to='SchoolApp.schoolprofilemodel'),
        ),
    ]
