# Generated by Django 6.0.5 on 2026-05-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_schoolprofilemodel_students'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='schoolName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolName', to='SchoolApp.schoolprofilemodel'),
        ),
    ]
