# Generated by Django 6.0.5 on 2026-05-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_attendancereport_staff_attendancereport_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='staff',
            new_name='teacher',
        ),
    ]
