# Generated by Django 6.0.5 on 2026-05-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_rename_subjectid_attendance_subject_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceSubjectModel',
        ),
    ]
