# Generated by Django 6.0.5 on 2026-05-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_studentprofilemodel_schoolname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='phoneNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='studentClass',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
