# Generated by Django 6.0.5 on 2026-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_rename_attendance_attendancesubjectmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesubjectmodel',
            options={'verbose_name_plural': 'Subject Based on Attendance'},
        ),
        migrations.RemoveField(
            model_name='studentprofilemodel',
            name='studentClass',
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='steamClass',
            field=models.CharField(choices=[('XI', 'XI'), ('XII', 'XII')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
