# Generated by Django 6.0.5 on 2026-05-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_alter_attendancesubjectmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='attendanceId',
            new_name='attendance',
        ),
    ]
