# Generated by Django 6.0.5 on 2026-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_alter_studentprofilemodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
