# Generated by Django 6.0.5 on 2026-06-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_alter_studentprofilemodel_stuclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='stuclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentclass'),
        ),
    ]
