# Generated by Django 6.0.5 on 2026-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_alter_studentprofilemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='phoneNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
