# Generated by Django 6.0.5 on 2026-05-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0006_alter_studentprofilemodel_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='phoneNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='studentClass',
            field=models.CharField(max_length=50),
        ),
    ]
