# Generated by Django 6.0.5 on 2026-05-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0009_emailschoolnotificationmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailschoolnotificationmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='emailschoolnotificationmodel',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentprofilemodel'),
            preserve_default=False,
        ),
    ]
