# Generated by Django 6.0.5 on 2026-05-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_alter_schoolprofilemodel_schoolphoneno'),
        ('StudentApp', '0011_remove_emailschoolnotificationmodel_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailschoolnotificationmodel',
            name='schoolName',
        ),
        migrations.AlterField(
            model_name='emailschoolnotificationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.schoolprofilemodel'),
        ),
    ]
