# Generated by Django 6.0.5 on 2026-05-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0012_remove_emailschoolnotificationmodel_schoolname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSchoolNotificationModel',
        ),
    ]
