# Generated by Django 6.0.5 on 2026-05-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0014_sessionmodel_subjectmodel_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='admin',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentprofilemodel'),
            preserve_default=False,
        ),
    ]
