# Generated by Django 6.0.5 on 2026-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('student', 'student'), ('school', 'school'), ('teacher', 'teacher')], max_length=50),
        ),
    ]
