# Generated by Django 6.0.5 on 2026-05-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
