# Generated by Django 6.0.6 on 2026-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_user_isverified_user_otp_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
