# Generated by Django 6.0.5 on 2026-05-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0008_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
