# Generated by Django 6.0.5 on 2026-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0009_delete_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('school', 'school'), ('teacher', 'teacher')], default='admin', max_length=50),
        ),
    ]
